name: typofixer-es
parent: default
matches:
- triggers:
  - Carcas
  replace: Caracas
  propagate_case: true
  word: true
- triggers:
  - aveces
  replace: a veces
  propagate_case: true
  word: true
- triggers:
  - haber
  replace: a ver
  propagate_case: true
  word: true
- triggers:
  - abandoran
  - abandoanr
  replace: abandonar
  propagate_case: true
  word: true
- triggers:
  - aca
  replace: acá
  propagate_case: true
  word: true
- triggers:
  - ademas
  replace: además
  propagate_case: true
  word: true
- triggers:
  - addios
  replace: adios
  propagate_case: true
  word: true
- triggers:
  - adulterdo
  replace: adulterado
  propagate_case: true
  word: true
- triggers:
  - aficion
  replace: afición
  propagate_case: true
  word: true
- triggers:
  - afirmasión
  replace: afirmación
  propagate_case: true
  word: true
- triggers:
  - ay
  replace: ahí
  propagate_case: true
  word: true
- triggers:
  - alegria
  replace: alegría
  propagate_case: true
  word: true
- triggers:
  - aleman
  replace: alemán
  propagate_case: true
  word: true
- triggers:
  - alli
  replace: allí
  propagate_case: true
  word: true
- triggers:
  - alunmos
  replace: alumnos
  propagate_case: true
  word: true
- triggers:
  - amorso
  replace: amoroso
  propagate_case: true
  word: true
- triggers:
  - analisis
  replace: análisis
  propagate_case: true
  word: true
- triggers:
  - aprarce
  replace: aparece
  propagate_case: true
  word: true
- triggers:
  - aqui
  replace: aquí
  propagate_case: true
  word: true
- triggers:
  - articulo
  replace: artículo
  propagate_case: true
  word: true
- triggers:
  - asi
  replace: así
  propagate_case: true
  word: true
- triggers:
  - atencion
  replace: atención
  propagate_case: true
  word: true
- triggers:
  - atras
  replace: atrás
  propagate_case: true
  word: true
- triggers:
  - avansar
  replace: avanzar
  propagate_case: true
  word: true
- triggers:
  - adversión
  replace: aversión
  propagate_case: true
  word: true
- triggers:
  - avion
  replace: avión
  propagate_case: true
  word: true
- triggers:
  - hay
  replace: ay
  propagate_case: true
  word: true
- triggers:
  - ayudrate
  replace: ayudarte
  propagate_case: true
  word: true
- triggers:
  - aereo
  replace: aéreo
  propagate_case: true
  word: true
- triggers:
  - anadir
  replace: añadir
  propagate_case: true
  word: true
- triggers:
  - vajo
  replace: bajo
  propagate_case: true
  word: true
- triggers:
  - balcon
  replace: balcón
  propagate_case: true
  word: true
- triggers:
  - vanal
  replace: banal
  propagate_case: true
  word: true
- triggers:
  - bateria
  - vateria
  replace: batería
  propagate_case: true
  word: true
- triggers:
  - vello
  replace: bello
  propagate_case: true
  word: true
- triggers:
  - voca
  replace: boca
  propagate_case: true
  word: true
- triggers:
  - beuno
  replace: bueno
  propagate_case: true
  word: true
- triggers:
  - basico
  replace: básico
  propagate_case: true
  word: true
- triggers:
  - cafe
  replace: café
  propagate_case: true
  word: true
- triggers:
  - caye
  replace: calle
  propagate_case: true
  word: true
- triggers:
  - cantra
  replace: cantar
  propagate_case: true
  word: true
- triggers:
  - capasidad
  - capsidad
  replace: capacidad
  propagate_case: true
  word: true
- triggers:
  - capitulo
  replace: capítulo
  propagate_case: true
  word: true
- triggers:
  - caracter
  replace: carácter
  propagate_case: true
  word: true
- triggers:
  - cassa
  - kasa
  replace: casa
  propagate_case: true
  word: true
- triggers:
  - castano
  replace: castaño
  propagate_case: true
  word: true
- triggers:
  - catastrofe
  replace: catástrofe
  propagate_case: true
  word: true
- triggers:
  - casua
  replace: causa
  propagate_case: true
  word: true
- triggers:
  - llayó
  replace: cayó
  propagate_case: true
  word: true
- triggers:
  - casa
  - kas
  replace: caza
  propagate_case: true
  word: true
- triggers:
  - sepillo
  replace: cepillo
  propagate_case: true
  word: true
- triggers:
  - sero
  - zero
  replace: cero
  propagate_case: true
  word: true
- triggers:
  - cervesa
  - serveza
  replace: cerveza
  propagate_case: true
  word: true
- triggers:
  - cienca
  replace: ciencia
  propagate_case: true
  word: true
- triggers:
  - cientifico
  replace: científico
  propagate_case: true
  word: true
- triggers:
  - cojer
  replace: coger
  propagate_case: true
  word: true
- triggers:
  - coleccion
  replace: colección
  propagate_case: true
  word: true
- triggers:
  - conmenzar
  replace: comenzar
  propagate_case: true
  word: true
- triggers:
  - comite
  replace: comité
  propagate_case: true
  word: true
- triggers:
  - conumismo
  replace: comunismo
  propagate_case: true
  word: true
- triggers:
  - comun
  replace: común
  propagate_case: true
  word: true
- triggers:
  - consiensia
  - consiencia
  - consciencia
  - conciensia
  replace: conciencia
  propagate_case: true
  word: true
- triggers:
  - contendo
  replace: contento
  propagate_case: true
  word: true
- triggers:
  - convalescencia
  replace: convalecencia
  propagate_case: true
  word: true
- triggers:
  - conversion
  replace: conversión
  propagate_case: true
  word: true
- triggers:
  - conyontura
  replace: conyuntura
  propagate_case: true
  word: true
- triggers:
  - corazon
  replace: corazón
  propagate_case: true
  word: true
- triggers:
  - cuestion
  replace: cuestión
  propagate_case: true
  word: true
- triggers:
  - ciudar
  replace: cuidar
  propagate_case: true
  word: true
- triggers:
  - cumpleanos
  replace: cumpleaños
  propagate_case: true
  word: true
- triggers:
  - cuando
  replace: cuándo
  propagate_case: true
  word: true
- triggers:
  - cesped
  replace: césped
  propagate_case: true
  word: true
- triggers:
  - codigo
  replace: código
  propagate_case: true
  word: true
- triggers:
  - como
  replace: cómo
  propagate_case: true
  word: true
- triggers:
  - comprame
  replace: cómprame
  propagate_case: true
  word: true
- triggers:
  - dano
  replace: daño
  propagate_case: true
  word: true
- triggers:
  - desición
  replace: decisión
  propagate_case: true
  word: true
- triggers:
  - desempeno
  replace: desempeño
  propagate_case: true
  word: true
- triggers:
  - desabitado
  replace: deshabitado
  propagate_case: true
  word: true
- triggers:
  - desdecho
  - desecho
  replace: deshecho
  propagate_case: true
  word: true
- triggers:
  - desprenderce
  - depsenderse
  replace: desprenderse
  propagate_case: true
  word: true
- triggers:
  - despues
  replace: después
  propagate_case: true
  word: true
- triggers:
  - dificil
  replace: difícil
  propagate_case: true
  word: true
- triggers:
  - dimension
  replace: dimensión
  propagate_case: true
  word: true
- triggers:
  - direccion
  replace: dirección
  propagate_case: true
  word: true
- triggers:
  - disitintos
  replace: distintos
  propagate_case: true
  word: true
- triggers:
  - de
  replace: dé
  propagate_case: true
  word: true
- triggers:
  - dia
  replace: día
  propagate_case: true
  word: true
- triggers:
  - donde
  replace: dónde
  propagate_case: true
  word: true
- triggers:
  - duo
  replace: dúo
  propagate_case: true
  word: true
- triggers:
  - hecho
  replace: echo
  propagate_case: true
  word: true
- triggers:
  - edicion
  replace: edición
  propagate_case: true
  word: true
- triggers:
  - editorail
  replace: editorial
  propagate_case: true
  word: true
- triggers:
  - educacion
  replace: educación
  propagate_case: true
  word: true
- triggers:
  - efectiviad
  replace: efectividad
  propagate_case: true
  word: true
- triggers:
  - eleccion
  replace: elección
  propagate_case: true
  word: true
- triggers:
  - emocion
  replace: emoción
  propagate_case: true
  word: true
- triggers:
  - empeno
  replace: empeño
  propagate_case: true
  word: true
- triggers:
  - empiesza
  replace: empieza
  propagate_case: true
  word: true
- triggers:
  - energia
  replace: energía
  propagate_case: true
  word: true
- triggers:
  - enfermp
  replace: enfermo
  propagate_case: true
  word: true
- triggers:
  - enfretnarse
  replace: enfrentarse
  propagate_case: true
  word: true
- triggers:
  - enferente
  replace: enfrente
  propagate_case: true
  word: true
- triggers:
  - enojadp
  replace: enojado
  propagate_case: true
  word: true
- triggers:
  - ensenar
  replace: enseñar
  propagate_case: true
  word: true
- triggers:
  - envio
  replace: envío
  propagate_case: true
  word: true
- triggers:
  - espisodios
  replace: episodios
  propagate_case: true
  word: true
- triggers:
  - escojer
  replace: escoger
  propagate_case: true
  word: true
- triggers:
  - excéptico
  replace: escéptico
  propagate_case: true
  word: true
- triggers:
  - espanol
  replace: español
  propagate_case: true
  word: true
- triggers:
  - esperamso
  replace: esperamos
  propagate_case: true
  word: true
- triggers:
  - estimaods
  - estimaos
  replace: estimados
  propagate_case: true
  word: true
- triggers:
  - estubiera
  replace: estuviera
  propagate_case: true
  word: true
- triggers:
  - exalar
  replace: exhalar
  propagate_case: true
  word: true
- triggers:
  - exausto
  replace: exhausto
  propagate_case: true
  word: true
- triggers:
  - exortar
  replace: exhortar
  propagate_case: true
  word: true
- triggers:
  - exumar
  replace: exhumar
  propagate_case: true
  word: true
- triggers:
  - familai
  replace: familia
  propagate_case: true
  word: true
- triggers:
  - fideligno
  replace: fidedigno
  propagate_case: true
  word: true
- triggers:
  - frotnera
  replace: frontera
  propagate_case: true
  word: true
- triggers:
  - facil
  replace: fácil
  propagate_case: true
  word: true
- triggers:
  - garage
  replace: garaje
  propagate_case: true
  word: true
- triggers:
  - genral
  - jeneral
  - keneral
  replace: general
  propagate_case: true
  word: true
- triggers:
  - jente
  - kente
  replace: gente
  propagate_case: true
  word: true
- triggers:
  - glosairo
  replace: glosario
  propagate_case: true
  word: true
- triggers:
  - gracas
  - grazias
  replace: gracias
  propagate_case: true
  word: true
- triggers:
  - gusanso
  replace: gusano
  propagate_case: true
  word: true
- triggers:
  - aber
  replace: haber
  propagate_case: true
  word: true
- triggers:
  - azer
  - acer
  replace: hacer
  propagate_case: true
  word: true
- triggers:
  - ay
  - ahí
  replace: hay
  propagate_case: true
  word: true
- triggers:
  - halla
  replace: haya
  propagate_case: true
  word: true
- triggers:
  - echo
  replace: hecho
  propagate_case: true
  word: true
- triggers:
  - human
  replace: humano
  propagate_case: true
  word: true
- triggers:
  - habil
  replace: hábil
  propagate_case: true
  word: true
- triggers:
  - idiocincracia
  replace: idiocincrasia
  propagate_case: true
  word: true
- triggers:
  - iluisón
  replace: ilusión
  propagate_case: true
  word: true
- triggers:
  - infanca
  replace: infancia
  propagate_case: true
  word: true
- triggers:
  - inflingido
  replace: infligido
  propagate_case: true
  word: true
- triggers:
  - ingerencia
  replace: injerencia
  propagate_case: true
  word: true
- triggers:
  - insistr
  - incistir
  replace: insistir
  propagate_case: true
  word: true
- triggers:
  - interesnate
  replace: interesante
  propagate_case: true
  word: true
- triggers:
  - interez
  replace: interés
  propagate_case: true
  word: true
- triggers:
  - goven
  - hoven
  replace: joven
  propagate_case: true
  word: true
- triggers:
  - lleyó
  replace: leyó
  propagate_case: true
  word: true
- triggers:
  - yamar
  replace: llamar
  propagate_case: true
  word: true
- triggers:
  - yave
  replace: llave
  propagate_case: true
  word: true
- triggers:
  - yeno
  replace: lleno
  propagate_case: true
  word: true
- triggers:
  - llroar
  - yorar
  replace: llorar
  propagate_case: true
  word: true
- triggers:
  - lapiz
  replace: lápiz
  propagate_case: true
  word: true
- triggers:
  - mama
  replace: mamá
  propagate_case: true
  word: true
- triggers:
  - misógeno
  replace: misógino
  propagate_case: true
  word: true
- triggers:
  - meustra
  replace: muestra
  propagate_case: true
  word: true
- triggers:
  - mas
  replace: más
  propagate_case: true
  word: true
- triggers:
  - mi
  replace: mí
  propagate_case: true
  word: true
- triggers:
  - móbil
  replace: móvil
  propagate_case: true
  word: true
- triggers:
  - nosotrs
  replace: nosotros
  propagate_case: true
  word: true
- triggers:
  - novedaes
  replace: novedades
  propagate_case: true
  word: true
- triggers:
  - neustra
  replace: nuestra
  propagate_case: true
  word: true
- triggers:
  - neuvo
  replace: nuevo
  propagate_case: true
  word: true
- triggers:
  - ocación
  replace: ocasión
  propagate_case: true
  word: true
- triggers:
  - holor
  replace: olor
  propagate_case: true
  word: true
- triggers:
  - papa
  replace: papá
  propagate_case: true
  word: true
- triggers:
  - pra
  replace: para
  propagate_case: true
  word: true
- triggers:
  - pes
  - vez
  replace: pez
  propagate_case: true
  word: true
- triggers:
  - plajio
  replace: plagio
  propagate_case: true
  word: true
- triggers:
  - preparadso
  replace: preparados
  propagate_case: true
  word: true
- triggers:
  - preción
  replace: presión
  propagate_case: true
  word: true
- triggers:
  - prsetarnos
  replace: prestarnos
  propagate_case: true
  word: true
- triggers:
  - preveer
  replace: prever
  propagate_case: true
  word: true
- triggers:
  - professor
  replace: profesor
  propagate_case: true
  word: true
- triggers:
  - proihibido
  - proibido
  replace: prohibido
  propagate_case: true
  word: true
- triggers:
  - puevlo
  replace: pueblo
  propagate_case: true
  word: true
- triggers:
  - que
  replace: qué
  propagate_case: true
  word: true
- triggers:
  - realiad
  replace: realidad
  propagate_case: true
  word: true
- triggers:
  - rejalo
  - rekalo
  replace: regalo
  propagate_case: true
  word: true
- triggers:
  - relasion
  - relacions
  replace: relaciones
  propagate_case: true
  word: true
- triggers:
  - resvalando
  replace: resbalando
  propagate_case: true
  word: true
- triggers:
  - ruputura
  replace: ruptura
  propagate_case: true
  word: true
- triggers:
  - rapido
  replace: rápido
  propagate_case: true
  word: true
- triggers:
  - saver
  - zaber
  replace: saber
  propagate_case: true
  word: true
- triggers:
  - sakapuntas
  replace: sacapuntas
  propagate_case: true
  word: true
- triggers:
  - ceis
  - zeis
  replace: seis
  propagate_case: true
  word: true
- triggers:
  - socail
  replace: social
  propagate_case: true
  word: true
- triggers:
  - sosiedad
  - socieda
  replace: sociedad
  propagate_case: true
  word: true
- triggers:
  - sofa
  replace: sofá
  propagate_case: true
  word: true
- triggers:
  - soldedad
  - solaedad
  replace: soledad
  propagate_case: true
  word: true
- triggers:
  - solidairo
  replace: solidario
  propagate_case: true
  word: true
- triggers:
  - si
  replace: sí
  propagate_case: true
  word: true
- triggers:
  - tabien
  - tambien
  - tambièn
  replace: también
  propagate_case: true
  word: true
- triggers:
  - temrinaba
  replace: terminaba
  propagate_case: true
  word: true
- triggers:
  - teinda
  replace: tienda
  propagate_case: true
  word: true
- triggers:
  - todabía
  replace: todavía
  propagate_case: true
  word: true
- triggers:
  - trabaho
  - trabago
  replace: trabajo
  propagate_case: true
  word: true
- triggers:
  - traduciods
  - traducidso
  replace: traducidos
  propagate_case: true
  word: true
- triggers:
  - traspsan
  replace: traspasan
  propagate_case: true
  word: true
- triggers:
  - traspsar
  replace: traspasar
  propagate_case: true
  word: true
- triggers:
  - transtornado
  replace: trastornado
  propagate_case: true
  word: true
- triggers:
  - te
  replace: té
  propagate_case: true
  word: true
- triggers:
  - tóxisac
  replace: tóxicas
  propagate_case: true
  word: true
- triggers:
  - tu
  replace: tú
  propagate_case: true
  word: true
- triggers:
  - unidso
  replace: unidos
  propagate_case: true
  word: true
- triggers:
  - baca
  replace: vaca
  propagate_case: true
  word: true
- triggers:
  - vacasiones
  - vacasions
  replace: vacaciones
  propagate_case: true
  word: true
- triggers:
  - baya
  replace: valla
  propagate_case: true
  word: true
- triggers:
  - balar
  replace: valor
  propagate_case: true
  word: true
- triggers:
  - baya
  - valla
  replace: vaya
  propagate_case: true
  word: true
- triggers:
  - bibe
  replace: vive
  propagate_case: true
  word: true
- triggers:
  - bivo
  replace: vivo
  propagate_case: true
  word: true
- triggers:
  - bolar
  replace: volar
  propagate_case: true
  word: true
- triggers:
  - llendo
  replace: yendo
  propagate_case: true
  word: true
- triggers:
  - sapato
  - capato
  replace: zapato
  propagate_case: true
  word: true
- triggers:
  - angulo
  replace: ángulo
  propagate_case: true
  word: true
- triggers:
  - arbol
  replace: árbol
  propagate_case: true
  word: true
- triggers:
  - el
  replace: él
  propagate_case: true
  word: true
- triggers:
  - elite
  replace: élite
  propagate_case: true
  word: true
- triggers:
  - epoca
  replace: época
  propagate_case: true
  word: true
- triggers:
  - exito
  replace: éxito
  propagate_case: true
  word: true
- triggers:
  - ultimo
  replace: último
  propagate_case: true
  word: true
