name: typofixer-fr
parent: default
matches:
- triggers:
  - cène
  replace: Cène
  propagate_case: true
  word: true
- triggers:
  - Guyana
  replace: Guiana
  propagate_case: true
  word: true
- triggers:
  - Israëlien
  replace: Israélien
  propagate_case: true
  word: true
- triggers:
  - Israëliens
  replace: Israéliens
  propagate_case: true
  word: true
- triggers:
  - à
  replace: a
  propagate_case: true
  word: true
- triggers:
  - academie
  replace: académie
  propagate_case: true
  word: true
- triggers:
  - aggression
  replace: agression
  propagate_case: true
  word: true
- triggers:
  - ale
  - allè
  replace: allé
  propagate_case: true
  word: true
- triggers:
  - arrivee
  replace: arrivée
  propagate_case: true
  word: true
- triggers:
  - arreter
  replace: arrêter
  propagate_case: true
  word: true
- triggers:
  - ascenceur
  replace: ascenseur
  propagate_case: true
  word: true
- triggers:
  - autorite
  replace: autorité
  propagate_case: true
  word: true
- triggers:
  - banlieu
  replace: banlieue
  propagate_case: true
  word: true
- triggers:
  - banlieux
  replace: banlieues
  propagate_case: true
  word: true
- triggers:
  - belle-soeur
  replace: belle-sœur
  propagate_case: true
  word: true
- triggers:
  - bitter
  replace: biter
  propagate_case: true
  word: true
- triggers:
  - bleux
  replace: bleus
  propagate_case: true
  word: true
- triggers:
  - blame
  replace: blâme
  propagate_case: true
  word: true
- triggers:
  - ble
  replace: blé
  propagate_case: true
  word: true
- triggers:
  - bruler
  replace: brûler
  propagate_case: true
  word: true
- triggers:
  - bugétaire
  replace: budgétaire
  propagate_case: true
  word: true
- triggers:
  - batiment
  replace: bâtiment
  propagate_case: true
  word: true
- triggers:
  - cest
  - ces
  - ses
  replace: c'est
  propagate_case: true
  word: true
- triggers:
  - cafe
  replace: café
  propagate_case: true
  word: true
- triggers:
  - casress
  replace: caresse
  propagate_case: true
  word: true
- triggers:
  - cathéchisme
  replace: catéchisme
  propagate_case: true
  word: true
- triggers:
  - cauchemard
  replace: cauchemar
  propagate_case: true
  word: true
- triggers:
  - cauchemards
  replace: cauchemars
  propagate_case: true
  word: true
- triggers:
  - ses
  - c'est
  replace: ces
  propagate_case: true
  word: true
- triggers:
  - championat
  replace: championnat
  propagate_case: true
  word: true
- triggers:
  - chretien
  replace: chrétien
  propagate_case: true
  word: true
- triggers:
  - chere
  replace: chère
  propagate_case: true
  word: true
- triggers:
  - cidessus
  replace: ci-dessus
  propagate_case: true
  word: true
- triggers:
  - cloitre
  replace: cloître
  propagate_case: true
  word: true
- triggers:
  - cle
  replace: clé
  propagate_case: true
  word: true
- triggers:
  - college
  replace: collège
  propagate_case: true
  word: true
- triggers:
  - colocateur
  replace: colocataire
  propagate_case: true
  word: true
- triggers:
  - collophane
  replace: colophane
  propagate_case: true
  word: true
- triggers:
  - colere
  replace: colère
  propagate_case: true
  word: true
- triggers:
  - comite
  replace: comité
  propagate_case: true
  word: true
- triggers:
  - compétivité
  replace: compétitivité
  propagate_case: true
  word: true
- triggers:
  - comedie
  replace: comédie
  propagate_case: true
  word: true
- triggers:
  - congres
  replace: congrès
  propagate_case: true
  word: true
- triggers:
  - connaitre
  replace: connaître
  propagate_case: true
  word: true
- triggers:
  - concience
  replace: conscience
  propagate_case: true
  word: true
- triggers:
  - considerer
  replace: considérer
  propagate_case: true
  word: true
- triggers:
  - consequence
  replace: conséquence
  propagate_case: true
  word: true
- triggers:
  - controle
  replace: contrôle
  propagate_case: true
  word: true
- triggers:
  - controler
  replace: contrôler
  propagate_case: true
  word: true
- triggers:
  - convie
  replace: convié
  propagate_case: true
  word: true
- triggers:
  - croissement
  replace: croisement
  propagate_case: true
  word: true
- triggers:
  - croitre
  replace: croître
  propagate_case: true
  word: true
- triggers:
  - crane
  replace: crâne
  propagate_case: true
  word: true
- triggers:
  - creme
  replace: crème
  propagate_case: true
  word: true
- triggers:
  - creance
  replace: créance
  propagate_case: true
  word: true
- triggers:
  - creature
  replace: créature
  propagate_case: true
  word: true
- triggers:
  - credit
  replace: crédit
  propagate_case: true
  word: true
- triggers:
  - cee
  replace: crée
  propagate_case: true
  word: true
- triggers:
  - creer
  replace: créer
  propagate_case: true
  word: true
- triggers:
  - crete
  replace: crête
  propagate_case: true
  word: true
- triggers:
  - cedille
  replace: cédille
  propagate_case: true
  word: true
- triggers:
  - ceramique
  replace: céramique
  propagate_case: true
  word: true
- triggers:
  - colon
  replace: côlon
  propagate_case: true
  word: true
- triggers:
  - colons
  replace: côlons
  propagate_case: true
  word: true
- triggers:
  - degre
  replace: degré
  propagate_case: true
  word: true
- triggers:
  - derniere
  replace: dernière
  propagate_case: true
  word: true
- triggers:
  - derriere
  replace: derrière
  propagate_case: true
  word: true
- triggers:
  - disparaitre
  replace: disparaître
  propagate_case: true
  word: true
- triggers:
  - débarasser
  replace: débarrasser
  propagate_case: true
  word: true
- triggers:
  - debats
  replace: débat
  propagate_case: true
  word: true
- triggers:
  - debut
  replace: début
  propagate_case: true
  word: true
- triggers:
  - decevoir
  replace: décevoir
  propagate_case: true
  word: true
- triggers:
  - défète
  - défete
  replace: défaite
  propagate_case: true
  word: true
- triggers:
  - degat
  replace: dégât
  propagate_case: true
  word: true
- triggers:
  - dejeuner
  replace: déjeuner
  propagate_case: true
  word: true
- triggers:
  - deja
  - déja
  replace: déjà
  propagate_case: true
  word: true
- triggers:
  - deshydrogenase
  replace: déshydrogénase
  propagate_case: true
  word: true
- triggers:
  - ellesmêmes
  replace: elles-mêmes
  propagate_case: true
  word: true
- triggers:
  - entre-gens
  replace: entregent
  propagate_case: true
  word: true
- triggers:
  - entrepreunariat
  replace: entrepreneuriat
  propagate_case: true
  word: true
- triggers:
  - entrepot
  replace: entrepôt
  propagate_case: true
  word: true
- triggers:
  - espece
  replace: espèce
  propagate_case: true
  word: true
- triggers:
  - esperer
  replace: espérer
  propagate_case: true
  word: true
- triggers:
  - et
  replace: est
  propagate_case: true
  word: true
- triggers:
  - est
  replace: et
  propagate_case: true
  word: true
- triggers:
  - ect.
  replace: etc.
  propagate_case: true
  word: true
- triggers:
  - experimental
  replace: expérimental
  propagate_case: true
  word: true
- triggers:
  - fachisme
  replace: fascisme
  propagate_case: true
  word: true
- triggers:
  - fachismes
  replace: fascismes
  propagate_case: true
  word: true
- triggers:
  - fachiste
  replace: fasciste
  propagate_case: true
  word: true
- triggers:
  - fachistes
  replace: fascistes
  propagate_case: true
  word: true
- triggers:
  - flotilles
  replace: flotrilles
  propagate_case: true
  word: true
- triggers:
  - flotille
  replace: flottille
  propagate_case: true
  word: true
- triggers:
  - fœhn
  replace: foehn
  propagate_case: true
  word: true
- triggers:
  - içi
  replace: ici
  propagate_case: true
  word: true
- triggers:
  - inclu
  replace: inclus
  propagate_case: true
  word: true
- triggers:
  - lipofucsine
  replace: lipofuscine
  propagate_case: true
  word: true
- triggers:
  - ma
  replace: m'a
  propagate_case: true
  word: true
- triggers:
  - m'a
  replace: ma
  propagate_case: true
  word: true
- triggers:
  - mange
  - mangè
  - manger
  replace: mangé
  propagate_case: true
  word: true
- triggers:
  - merçi
  replace: merci
  propagate_case: true
  word: true
- triggers:
  - merveilleu
  replace: merveilleux
  propagate_case: true
  word: true
- triggers:
  - nivau
  replace: niveau
  propagate_case: true
  word: true
- triggers:
  - ont
  replace: 'on'
  propagate_case: true
  word: true
- triggers:
  - 'on'
  replace: ont
  propagate_case: true
  word: true
- triggers:
  - ou
  replace: où
  propagate_case: true
  word: true
- triggers:
  - par ci
  replace: par-ci
  propagate_case: true
  word: true
- triggers:
  - par la
  replace: par-la
  propagate_case: true
  word: true
- triggers:
  - parle
  - parlè
  - parler
  replace: parlé
  propagate_case: true
  word: true
- triggers:
  - patin à roues
  replace: patin à roulettes
  propagate_case: true
  word: true
- triggers:
  - pendre la crémallière
  replace: pendre la crémaillère
  propagate_case: true
  word: true
- triggers:
  - peut être
  replace: peut-être
  propagate_case: true
  word: true
- triggers:
  - pouasse
  replace: poisse
  propagate_case: true
  word: true
- triggers:
  - pourpalers
  replace: pourparlers
  propagate_case: true
  word: true
- triggers:
  - protége
  replace: protège
  propagate_case: true
  word: true
- triggers:
  - qualitée
  replace: qualité
  propagate_case: true
  word: true
- triggers:
  - rôder
  replace: roder
  propagate_case: true
  word: true
- triggers:
  - sa
  replace: s'a
  propagate_case: true
  word: true
- triggers:
  - s'a
  replace: sa
  propagate_case: true
  word: true
- triggers:
  - saynette
  replace: saynète
  propagate_case: true
  word: true
- triggers:
  - c'est
  - ces
  replace: ses
  propagate_case: true
  word: true
- triggers:
  - soit-disant
  replace: soi-disant
  propagate_case: true
  word: true
- triggers:
  - sont
  replace: son
  propagate_case: true
  word: true
- triggers:
  - sont
  replace: sons
  propagate_case: true
  word: true
- triggers:
  - son
  - sons
  replace: sont
  propagate_case: true
  word: true
- triggers:
  - ta
  replace: t'a
  propagate_case: true
  word: true
- triggers:
  - t'a
  replace: ta
  propagate_case: true
  word: true
- triggers:
  - the
  replace: thé
  propagate_case: true
  word: true
- triggers:
  - transexuel
  replace: transsexuel
  propagate_case: true
  word: true
- triggers:
  - transexuels
  replace: transsexuels
  propagate_case: true
  word: true
- triggers:
  - trompe l'oeil
  replace: trompe-l’œil
  propagate_case: true
  word: true
- triggers:
  - a
  replace: à
  propagate_case: true
  word: true
- triggers:
  - ca
  - sa
  replace: ça
  propagate_case: true
  word: true
- triggers:
  - ça et là
  replace: çà et là
  propagate_case: true
  word: true
- triggers:
  - etaient
  replace: étaient
  propagate_case: true
  word: true
- triggers:
  - etait
  replace: était
  propagate_case: true
  word: true
- triggers:
  - etaits
  replace: étaits
  propagate_case: true
  word: true
- triggers:
  - etranger
  replace: étranger
  propagate_case: true
  word: true
- triggers:
  - etudier
  replace: étudier
  propagate_case: true
  word: true
- triggers:
  - ete
  - eté
  replace: été
  propagate_case: true
  word: true
- triggers:
  - etre
  replace: être
  propagate_case: true
  word: true
- triggers:
  - ilôt
  replace: îlot
  propagate_case: true
  word: true
