name: typofixer-fr
parent: default
matches:
- trigger: cène
  replace: Cène
  propagate_case: true
  word: true
- trigger: Guyana
  replace: Guiana
  propagate_case: true
  word: true
- trigger: Israëlien
  replace: Israélien
  propagate_case: true
  word: true
- trigger: Israëliens
  replace: Israéliens
  propagate_case: true
  word: true
- trigger: aggression
  replace: agression
  propagate_case: true
  word: true
- trigger: arreter
  replace: arrêter
  propagate_case: true
  word: true
- trigger: ascenceur
  replace: ascenseur
  propagate_case: true
  word: true
- trigger: banlieu
  replace: banlieue
  propagate_case: true
  word: true
- trigger: banlieux
  replace: banlieues
  propagate_case: true
  word: true
- trigger: belle-soeur
  replace: belle-sœur
  propagate_case: true
  word: true
- trigger: bitter
  replace: biter
  propagate_case: true
  word: true
- trigger: bleux
  replace: bleus
  propagate_case: true
  word: true
- trigger: bugétaire
  replace: budgétaire
  propagate_case: true
  word: true
- trigger: casress
  replace: caresse
  propagate_case: true
  word: true
- trigger: cathéchisme
  replace: catéchisme
  propagate_case: true
  word: true
- trigger: cauchemard
  replace: cauchemar
  propagate_case: true
  word: true
- trigger: cauchemards
  replace: cauchemars
  propagate_case: true
  word: true
- trigger: championat
  replace: championnat
  propagate_case: true
  word: true
- trigger: cidessus
  replace: ci-dessus
  propagate_case: true
  word: true
- trigger: colocateur
  replace: colocataire
  propagate_case: true
  word: true
- trigger: collophane
  replace: colophane
  propagate_case: true
  word: true
- trigger: compétivité
  replace: compétitivité
  propagate_case: true
  word: true
- trigger: concience
  replace: conscience
  propagate_case: true
  word: true
- trigger: croissement
  replace: croisement
  propagate_case: true
  word: true
- trigger: colon
  replace: côlon
  propagate_case: true
  word: true
- trigger: colons
  replace: côlons
  propagate_case: true
  word: true
- trigger: derniere
  replace: dernière
  propagate_case: true
  word: true
- trigger: débarasser
  replace: débarrasser
  propagate_case: true
  word: true
- trigger: défète
  replace: défaite
  propagate_case: true
  word: true
- trigger: défete
  replace: défaite
  propagate_case: true
  word: true
- trigger: deshydrogenase
  replace: déshydrogénase
  propagate_case: true
  word: true
- trigger: ellesmêmes
  replace: elles-mêmes
  propagate_case: true
  word: true
- trigger: entre-gens
  replace: entregent
  propagate_case: true
  word: true
- trigger: entrepreunariat
  replace: entrepreneuriat
  propagate_case: true
  word: true
- trigger: ect.
  replace: etc.
  propagate_case: true
  word: true
- trigger: experimental
  replace: expérimental
  propagate_case: true
  word: true
- trigger: fachisme
  replace: fascisme
  propagate_case: true
  word: true
- trigger: fachismes
  replace: fascismes
  propagate_case: true
  word: true
- trigger: fachiste
  replace: fasciste
  propagate_case: true
  word: true
- trigger: fachistes
  replace: fascistes
  propagate_case: true
  word: true
- trigger: flotilles
  replace: flotrilles
  propagate_case: true
  word: true
- trigger: flotille
  replace: flottille
  propagate_case: true
  word: true
- trigger: fœhn
  replace: foehn
  propagate_case: true
  word: true
- trigger: içi
  replace: ici
  propagate_case: true
  word: true
- trigger: inclu
  replace: inclus
  propagate_case: true
  word: true
- trigger: lipofucsine
  replace: lipofuscine
  propagate_case: true
  word: true
- trigger: merçi
  replace: merci
  propagate_case: true
  word: true
- trigger: merveilleu
  replace: merveilleux
  propagate_case: true
  word: true
- trigger: nivau
  replace: niveau
  propagate_case: true
  word: true
- trigger: par ci
  replace: par-ci
  propagate_case: true
  word: true
- trigger: par la
  replace: par-la
  propagate_case: true
  word: true
- trigger: patin à roues
  replace: patin à roulettes
  propagate_case: true
  word: true
- trigger: pendre la crémallière
  replace: pendre la crémaillère
  propagate_case: true
  word: true
- trigger: peut être
  replace: peut-être
  propagate_case: true
  word: true
- trigger: pouasse
  replace: poisse
  propagate_case: true
  word: true
- trigger: pourpalers
  replace: pourparlers
  propagate_case: true
  word: true
- trigger: protége
  replace: protège
  propagate_case: true
  word: true
- trigger: qualitée
  replace: qualité
  propagate_case: true
  word: true
- trigger: rôder
  replace: roder
  propagate_case: true
  word: true
- trigger: saynette
  replace: saynète
  propagate_case: true
  word: true
- trigger: soit-disant
  replace: soi-disant
  propagate_case: true
  word: true
- trigger: transexuel
  replace: transsexuel
  propagate_case: true
  word: true
- trigger: transexuels
  replace: transsexuels
  propagate_case: true
  word: true
- trigger: trompe l'oeil
  replace: trompe-l’œil
  propagate_case: true
  word: true
- trigger: ça et là
  replace: çà et là
  propagate_case: true
  word: true
- trigger: etaient
  replace: étaient
  propagate_case: true
  word: true
- trigger: etait
  replace: était
  propagate_case: true
  word: true
- trigger: etaits
  replace: étaits
  propagate_case: true
  word: true
- trigger: etre
  replace: être
  propagate_case: true
  word: true
- trigger: ilôt
  replace: îlot
  propagate_case: true
  word: true
